SELECT CONCAT(NAME, '(',LEFT(OCCUPATION,1),')') AS NP
FROM OCCUPATIONS
ORDER BY NP;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION), ' ', LOWER(OCCUPATION), 's.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;
